# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'M3U8TOMP4Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for M3U8TOMP4Demo
  pod 'Alamofire', '~> 4.8.2'
end
